""" Constant for SSI datafeed """
API_URL = "https://fc-data.ssi.com.vn"
ENDPOINT_AUTH = "api/v2/Market/AccessToken"
ENDPOINT_SECURITIES = "api/v2/Market/Securities"
ENDPOINT_SECURITIES_DETAIL = "api/v2/Market/SecuritiesDetails"
ENDPOINT_INDEX_COMPONENT = "api/v2/Market/IndexComponents"
ENDPOINT_INDEX_LIST = "api/v2/Market/IndexList"
ENDPOINT_DAILY_INDEX = "api/v2/Market/DailyIndex"
ENDPOINT_INTRADAY_OHLC = "api/v2/Market/IntradayOHLC"
ENDPOINT_ENDOFDAY_OHLC = "api/v2/Market/DailyOHLC"
ENDPOINT_DAILY_STOCK_PRICE = "api/v2/Market/DailyStockPrice"

HUB_URL = "wss://fc-datahub.ssi.com.vn/v2.0/signalr"
HUB = "FcMarketDataV2hub"
